// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package th.ac.test;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import th.ac.test.Aest;
import th.ac.test.AestDataOnDemand;

privileged aspect AestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AestDataOnDemand: @Component;
    
    private Random AestDataOnDemand.rnd = new SecureRandom();
    
    private List<Aest> AestDataOnDemand.data;
    
    public Aest AestDataOnDemand.getNewTransientAest(int index) {
        Aest obj = new Aest();
        return obj;
    }
    
    public Aest AestDataOnDemand.getSpecificAest(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Aest obj = data.get(index);
        Long id = obj.getId();
        return Aest.findAest(id);
    }
    
    public Aest AestDataOnDemand.getRandomAest() {
        init();
        Aest obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Aest.findAest(id);
    }
    
    public boolean AestDataOnDemand.modifyAest(Aest obj) {
        return false;
    }
    
    public void AestDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Aest.findAestEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Aest' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Aest>();
        for (int i = 0; i < 10; i++) {
            Aest obj = getNewTransientAest(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
