// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package th.ac.test;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import th.ac.test.Aest;

privileged aspect Aest_Roo_Jpa_Entity {
    
    declare @type: Aest: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Aest.id;
    
    @Version
    @Column(name = "version")
    private Integer Aest.version;
    
    public Long Aest.getId() {
        return this.id;
    }
    
    public void Aest.setId(Long id) {
        this.id = id;
    }
    
    public Integer Aest.getVersion() {
        return this.version;
    }
    
    public void Aest.setVersion(Integer version) {
        this.version = version;
    }
    
}
