// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package th.ac.test;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import th.ac.test.Aest;

privileged aspect Aest_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Aest.entityManager;
    
    public static final EntityManager Aest.entityManager() {
        EntityManager em = new Aest().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Aest.countAests() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Aest o", Long.class).getSingleResult();
    }
    
    public static List<Aest> Aest.findAllAests() {
        return entityManager().createQuery("SELECT o FROM Aest o", Aest.class).getResultList();
    }
    
    public static Aest Aest.findAest(Long id) {
        if (id == null) return null;
        return entityManager().find(Aest.class, id);
    }
    
    public static List<Aest> Aest.findAestEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Aest o", Aest.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Aest.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Aest.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Aest attached = Aest.findAest(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Aest.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Aest.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Aest Aest.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Aest merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
