// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package th.ac.test;

import org.springframework.beans.factory.annotation.Configurable;
import th.ac.test.Aest;

privileged aspect Aest_Roo_Configurable {
    
    declare @type: Aest: @Configurable;
    
}
